In [ ]:
import gensim


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import nltk
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
# # !pip install chardet
# import chardet

# story =[]
# for i in range(1, 6):
#   filename = f'00{i}ssb.txt'
#   with open(filename, 'rb') as f:
#     encoding = chardet.detect(f.read())['encoding']
#     f.seek(0)
#     lines = f.readlines()
#     for line in lines:
#       corpus.append(line.strip())

In [ ]:
story2 = []
for i in range(1, 6):
    filename = f"00{i}ssb.txt"
    with open(filename, 'r', encoding='iso-8859-1') as f:
        corpus = f.read()
        raw_sentences = sent_tokenize(corpus)
        for sentence in raw_sentences:
            processed_sentence = simple_preprocess(sentence)
            story2.append(processed_sentence)


In [ ]:
len(story2)

145020

In [ ]:
type(story2)

list

In [ ]:
model = gensim.models.Word2Vec(
    window = 10 ,
    min_count = 2,

)

In [ ]:
model.build_vocab(story2)   # to built vocabulary (extract unique words)

In [ ]:
model.train(story2 , total_examples = model.corpus_count,epochs = model.epochs)

(6569399, 8628190)

In [ ]:
model.wv.most_similar('daenerys')    # here WV mean word2Vec

[('stormborn', 0.8059345483779907),
 ('myrcella', 0.73862624168396),
 ('elia', 0.7245510816574097),
 ('targaryen', 0.7223405241966248),
 ('unburnt', 0.7157233953475952),
 ('margaery', 0.7141594290733337),
 ('princess', 0.7064969539642334),
 ('dorne', 0.6927937865257263),
 ('aegon', 0.689032256603241),
 ('joffrey', 0.6849123239517212)]

In [ ]:
model.wv.doesnt_match(['jon','rikon','robb','arya','sansa','bran'])

'jon'

In [ ]:
model.wv.doesnt_match(['cersei','jaime','bronn','tyrion'])

'bronn'

In [ ]:
model.wv['king']

array([ 2.4545972 ,  0.7415486 ,  1.3850276 ,  1.8722543 , -1.5483496 ,
        0.9947458 ,  0.56040925, -0.02874411, -1.6784492 , -0.84292567,
       -0.9576416 ,  0.53380585,  0.56846267,  2.0673985 , -2.6256363 ,
       -2.1313717 ,  0.01927886,  3.8172803 ,  1.4552836 ,  1.0940422 ,
        2.476216  , -1.7665093 ,  2.1486764 , -4.9588175 , -2.5587    ,
        1.3355587 , -2.0525527 , -2.985254  , -0.27640578,  1.2993209 ,
       -2.5729206 , -0.01589298,  0.3504154 , -1.7257173 ,  3.761942  ,
       -3.5295193 , -3.365313  , -1.2388731 ,  0.16247709, -0.8577089 ,
        1.0133195 ,  2.8640637 ,  2.5850532 ,  0.30026996, -0.34124348,
       -1.3815517 ,  0.86673766, -3.213876  ,  3.544866  , -2.5835054 ,
       -2.8673222 , -1.403678  , -0.701227  , -3.6880257 ,  2.6377628 ,
       -0.7417139 ,  0.37213457,  0.41198036,  0.0972279 ,  0.239169  ,
        0.85968345,  0.8302875 , -0.40090534,  1.41606   ,  0.75920635,
        0.5974734 , -0.96606046, -0.5615789 ,  0.07161183, -1.12

In [ ]:
model.wv['king'].shape     # it give 100 because by default 100 dimension is fixed
# but we can increase it upto 300 dimension

(100,)

In [ ]:
model.wv.similarity('arya','sansa')    # we will show similarity because both are sisters

0.85533994

In [ ]:
model.wv.similarity('cersei','sansa')    # we san show similarity because both are queen

0.7597968

In [ ]:
model.wv.similarity('tywin','sansa')    # ther are not any thing comon  so we will  show less similarity

0.26461047

In [ ]:
model.wv.get_normed_vectors()

array([[-0.04280302, -0.09554272,  0.10111125, ..., -0.11331674,
         0.03015802,  0.03014001],
       [-0.11072371, -0.08837039, -0.00780385, ..., -0.06999449,
        -0.02900665,  0.0348819 ],
       [ 0.17375124, -0.06210653, -0.0617493 , ..., -0.08454169,
         0.15263677, -0.11814282],
       ...,
       [ 0.01301058,  0.08632981, -0.07140955, ..., -0.04849895,
         0.05935424, -0.1760079 ],
       [-0.01501503,  0.10620502,  0.16351862, ...,  0.07929301,
         0.12818815, -0.14450885],
       [-0.07347512,  0.07170495,  0.072882  , ...,  0.01320052,
         0.08677686, -0.0740878 ]], dtype=float32)

In [ ]:
model.wv.get_normed_vectors().shape

(17453, 100)

In [ ]:
# now we will try to print graph
# at first we will decrease its dimentianality  by pca}

In [ ]:
y = model.wv.index_to_key

In [ ]:
len(y)  # total 17453 words stored in y

17453

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components = 3)

In [ ]:
x = pca.fit_transform (model.wv.get_normed_vectors())

In [ ]:
import  plotly.express as px


In [ ]:
fig = px.scatter_3d(x[:100],x=0 , y=1 , z=2,color = y[:100])

In [ ]:
fig.show()

In [ ]:
len(story2)

145020

In [ ]:
# NOw we will remove stopword  then see the result

In [ ]:
type(story2)

list

In [ ]:
sw_remov_story = []
# from nltk.corpus import stopwords
from nltk.corpus import stopwords
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
stopwords.words("english")""

SyntaxError: invalid syntax (<ipython-input-54-0b3df5490081>, line 1)

In [ ]:
storys =[story2[0],story2[1],story2[2]]


In [ ]:
storys

[['game',
  'of',
  'thrones',
  'book',
  'one',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'we',
  'should',
  'start',
  'back',
  'gared',
  'urged',
  'as',
  'the',
  'woods',
  'began',
  'to',
  'grow',
  'dark',
  'around',
  'them'],
 ['the', 'wildlings', 'are', 'dead'],
 ['do', 'the', 'dead', 'frighten', 'you']]

In [ ]:
sw_remov_story=[]
for sents in story2:
  temp=[]
  for word in sents:
    if word not in stopwords.words("english"):
      temp.append(word)
  sw_remov_story.append(temp)
sw_remov_story


[['game',
  'thrones',
  'book',
  'one',
  'song',
  'ice',
  'fire',
  'george',
  'martin',
  'prologue',
  'start',
  'back',
  'gared',
  'urged',
  'woods',
  'began',
  'grow',
  'dark',
  'around'],
 ['wildlings', 'dead'],
 ['dead', 'frighten'],
 ['ser', 'waymar', 'royce', 'asked', 'hint', 'smile'],
 ['gared', 'rise', 'bait'],
 ['old', 'man', 'past', 'fifty', 'seen', 'lordlings', 'come', 'go'],
 ['dead', 'dead', 'said'],
 ['business', 'dead'],
 ['dead'],
 ['royce', 'asked', 'softly'],
 ['proof'],
 ['saw', 'gared', 'said'],
 ['says', 'dead', 'proof', 'enough'],
 ['known', 'would', 'drag', 'quarrel', 'sooner', 'later'],
 ['wished', 'later', 'rather', 'sooner'],
 ['mother', 'told', 'dead', 'men', 'sing', 'songs', 'put'],
 ['wet', 'nurse', 'said', 'thing', 'royce', 'replied'],
 ['never', 'believe', 'anything', 'hear', 'woman', 'tit'],
 ['things', 'learned', 'even', 'dead'],
 ['voice', 'echoed', 'loud', 'twilit', 'forest'],
 ['page', 'long', 'ride', 'us', 'gared', 'pointed'],
 ['eig

In [ ]:
model2 = gensim.models.Word2Vec(
    window = 10 ,
    min_count = 2,
)

In [ ]:
model2.build_vocab(sw_remov_story)   # to built vocabulary (extract unique words)

In [ ]:
model2.train(sw_remov_story , total_examples = model.corpus_count,epochs = model.epochs)

(4396934, 4579390)

In [ ]:
model2.wv.most_similar('daenerys')    # here WV mean word2Vec

[('unburnt', 0.8599647879600525),
 ('stormborn', 0.8576905131340027),
 ('adultery', 0.8365490436553955),
 ('myrcella', 0.817697286605835),
 ('dorne', 0.8129498362541199),
 ('court', 0.8108464479446411),
 ('doran', 0.803479015827179),
 ('mellario', 0.7986115217208862),
 ('viserys', 0.7921466827392578),
 ('regent', 0.7893602848052979)]

In [ ]:
model.wv.most_similar('elia')    # here WV mean word2Vec

[('mercy', 0.9396836161613464),
 ('sure', 0.8958714008331299),
 ('stag', 0.889404833316803),
 ('yours', 0.8879602551460266),
 ('spirits', 0.8830434679985046),
 ('suspicion', 0.878025472164154),
 ('gasped', 0.8772451877593994),
 ('swirling', 0.8764211535453796),
 ('resisted', 0.87392258644104),
 ('gravely', 0.8734520673751831)]

In [ ]:
model2.wv.get_normed_vectors()

array([[ 0.05390063,  0.09878986,  0.01900647, ..., -0.07314514,
        -0.04388748,  0.20629522],
       [-0.2265941 ,  0.116607  ,  0.06389371, ..., -0.07140548,
        -0.13843569,  0.19958824],
       [ 0.01112913,  0.03873864, -0.01246797, ..., -0.17891122,
         0.11480854, -0.14537142],
       ...,
       [-0.0928111 ,  0.10098401,  0.04480052, ..., -0.19224797,
         0.05242506,  0.0974308 ],
       [-0.1377655 ,  0.13893013,  0.06291117, ..., -0.20702972,
         0.08616348,  0.12081271],
       [-0.14333247,  0.08178964,  0.07357074, ..., -0.17542575,
         0.06609174,  0.06795456]], dtype=float32)

In [ ]:
model2.wv.get_normed_vectors().shape

(17310, 100)

In [ ]:
y2 = model2.wv.index_to_key

In [ ]:
len(y2)

17310

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)

In [ ]:
x2 = pca.fit_transform (model2.wv.get_normed_vectors())

In [ ]:
import plotly.express as plt

In [ ]:
fig2 = px.scatter_3d(x2[:100],x=0 , y=1 , z=2,color = y2[:100])

In [ ]:
fig2.show()